spring:
  application:
    name: spring-boot-keycloak
  boot:
    admin:
      client:
        url: 'https://localhost:8083/spring-boot/'
        username: 'admin'
        password: 'admin'
        instance:
          metadata:
            user:
              name: 'admin'
              password: 'admin'
          name: '${spring.application.name}'
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: 'spring-boot-client'
            authorization-grant-type: 'authorization_code'
            scope:
              - 'openid'
              - 'profile'
              - 'roles'
              - 'email'
        provider:
          keycloak:
            issuer-uri: 'https://localhost:8443/realms/spring-boot-applications'
            user-name-attribute: 'preferred_username'

logging:
  level:
    org.springframework.security: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: 'https://localhost:8082/eureka'
    fetch-registry: true
    register-with-eureka: true
    region: eu-center
  instance:
    hostname: '${spring.application.name}'
    prefer-ip-address: true
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

server:
  error:
    whitelabel:
      enabled: false
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: changeit
    protocol: TLS
    enabled-protocols: TLSv1.3
    trust-store: classpath:truststore.p12
    trust-store-password: changeit
    key-password: changeit
    key-alias: localhost
  http2:
    enabled: true
  port: '8081'
  servlet:
    context-path: /